### PR TITLE
Add Docker-support

### PR DESCRIPTION
**Pull request by mre**
This adds support for running the forwarder inside Docker.
It does not work yet for some reason.
Can start the container, but it doesn't respond to
my requests. Needs some more testing...

### CODE REVIEW

**Comment by mre** [comment]
I will look into this again later today. My Docker for Mac runs out of disk space right now. Not sure what's going on but I don't think it's related to this image.

**Comment by woolfg** [comment]
seems to work on my machine
```
⎔ Starting a local server...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:35841/2410cc11-9f62-454a-83f4-1b20915fd10e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:inf] Worker reloaded! (1.26MiB)
[mf:wrn] Worker's uncompressed size exceeds the 1MiB limit! Note that your worker will be compressed during upload so you may still be able to deploy it.
[mf:inf] Listening on 0.0.0.0:9000
╭──────────────────────────────────────────────────────────╮
│ [ open a   [d open     [l turn off    [ clear    [x to   │
│ ]browser,    Devtools,   local mode,  ]console,    exit  │
│                                                          │
╰──────────────────────────────────────────────────────────╯
Tue Dec 06 2022 15:41:18 GMT+0000 (Coordinated Universal Time) - [/], located at: (45.4722, 9.1922), cf: Cf {
    inner: Cf {
        obj: Object {
            obj: JsValue(Object({"clientTcpRtt":34,"longitude":"9.19220","latitude":"45.47220",........."postalCode":"20138"})),
        },
    },
}
Received request from Unknown Podcast Client
GET / 200 OK (538.05ms)

**Review by woolfg — APPROVED** [review]
works on my machine :+1:

**Comment by mre** [comment]
LOL, I didn't expect that. Thanks for testing. Will merge and add as an optional component to `stack`.

**Pull request merged**
